#!/usr/bin/env bash

# Web servers are the piece of software generating and serving HTML pages, let’s install one!
# Installing technqiues and requirements

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
echo 'Hello World!' | sudo tee /var/www/html/index.html
sudo service nginx start
