#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx

sudo chown "$USER":"$USER" /var/www/html/index.html
echo 'Hello World!' > /var/www/html/index.html
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

sudo service nginx start
