#!/usr/bin/env bash
# A Bash script that configures  new Ubuntu machine to respect the requirements:
# Configure a new Nginx server so that /redirect_me is redirecting to another page.
# This scripts also configures the default webpage served to be "Hello World!"
# When request url matches /redirect_me, it redirects to my youtube channel.
# When a page/file not found in the document root is requested, the 404.html
# page is served to the client as stated with the error_page directive.

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
echo 'Hello World!' | sudo tee /var/www/html/index.html
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo mkdir -p /var/www/error
echo "Ceci n'est pas une page" | sudo tee /var/www/error/404.html
sudo sed -i '/server_name _/a error_page 404 /404.html; location = /404.html {root /var/www/error/;internal; }' /etc/nginx/sites-available/default
