#!/usr/bin/env bash
# Make a fix of a short and sweet connection to Ngnix start up.
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginx.pid
