#!/usr/bin/env bash
# Write a Bash script that displays the content of the file /etc/passwd.
# Displays username
# Displays user id
# Displays Home directory path for the user

while read -r line
do
	echo "$line" | cut -d: -f1,4,7
done < "/etc/passwd"
