#!/usr/bin/env bash
# This script is displaying "Best School" 10 times, using the while loop.
# in the 9th iteration, displays Best School and then Hi on a new line.

i=1

while [ $i -le 10 ]
do
	echo "Best School"

	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
	[ $((i++)) ]
done
