#!/usr/bin/env bash
# This script is displaying "Best School" 10 times, using the while loop.
# in the 9th iteration, displays Best School and then Hi on a new line.

i=1

while ((i < 10))
do
	if ((i == 9))
	then
		echo "Hi"
	fi
		echo "Best School"
		((i++))
done
