#!/usr/bin/env bash
# Configures a ufw through web-01 so that its firewall redirects port 8080/TCP to port 80/TCP

sudo ufw default deny incoming
sudo ufw allow ssh/tcp
sudo ufw allow 80/tcp
sudp ufw allow 443/tcp
sudo ufw enable
