#!/usr/bin/env bash
# A Bash scripting container so that Nginx is running as the nginx user.
# While nginx must be listening on all active IPs on port 8080.

sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill apache2
chmod 644 /etc/nginx/nginx.conf
sudo --user nginx service nginx start
