#!/usr/bin/env bash

ssh ubuntu@52.91.182.157 -i ~/.ssh/school
mkdir -p ~/.ssh && touch ~/.ssh/authorized_keys
chmod 700 ~/.ssh && chmod 600 ~/.ssh/authorized_keys
echo ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCiZ37DYL5mHtmAc1QmiPXN5G8dcR9zptsTAfkAbE6O7INi2UsTC95D/mwVTqUUkMjgZAKygVbexZOOMEuDzcJw4A6nfOp9xlA3C2wTiQJ3nMlzlxVd8cWaitYLm4lJUyT/S6+8ota8lQyNTC2izvXtP8Rmr8BsPCercUv538WMsv64zd6ZA2AGtNvewq3iOW0+DBeJnS1sG88J7PAXwT6iT5DJh7MidGst/BBxYiseCebQCbe5LS2Ri/AwITUgc3HpQG0PpcleOwd/YcT1TuYbYxyS+KfkRsvGNJkzpkzSuoDzep7VSJ2usg7iG3RbB0Naonl4LxNqScQK+6PsEUwSBwriE2t+/Vs7PYfxX3a5u+46f1+SCXFgN6Gh56BkO2Zdpr7zJ5gxL8ReFBLYs59Y8ibU72Ay9Qu7GHaJaEfN79untyvUVZ0K9aasx6EZO3sGr1uEjwD++mNKU7WK/YStXT+0NJruxkAAYDpPFSc+dLJZ1X0XcRjEZirtMnYh0iM= root@477083b675d7
